# Generated by Django 2.2.4 on 2020-01-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_userprofile_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dateofbirth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
