# Generated by Django 2.2.4 on 2020-01-10 16:45

import birthday.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_userprofile_dateofbirth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='dateofbirth',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birthday',
            field=birthday.fields.BirthdayField(default='2000-01-01'),
        ),
    ]
