# Generated by Django 2.2.4 on 2020-01-15 17:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0016_auto_20200111_2346'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EducationHistory',
            new_name='MusicEducation',
        ),
        migrations.DeleteModel(
            name='EmplyementHistory',
        ),
    ]
